# Generated by Django 4.2.5 on 2023-10-12 01:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_remove_blog_usuario_origen_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'categoria de blogs',
                'verbose_name_plural': 'categorias de blogs',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_corta', models.CharField(blank=True, max_length=200, null=True, verbose_name='descripción corta')),
                ('contenido', models.CharField(max_length=10000)),
                ('fecha_actualizacion', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.blogcategoria', verbose_name='categoría')),
                ('usuario_origen_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.perfil', verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
