# Generated by Django 4.2.5 on 2023-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='descripción'),
        ),
    ]
