# Generated by Django 4.2.5 on 2023-09-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_usuario_contraseña_blog_usuario_origen_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
