# Generated by Django 4.2.5 on 2023-10-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_delete_cliente_delete_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='usuario_origen_id',
        ),
    ]
