# Generated by Django 4.2.5 on 2023-10-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_delete_blog_perfil_biografia_alter_perfil_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
